import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
import { pageMetadata } from "@/lib/content";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = pageMetadata({
  title: "Terms of Service",
  description: `The terms that govern your use of ${LEGAL.companyName}: the service, your account, AI output, plans and renewal, email, copyright, your data and liability.`,
  path: "/terms",
});

/**
 * TEMPLATE TEXT. This is a placeholder so the route, the link and the
 * acceptance record exist; the wording is a legal task. Replace it before
 * anyone outside your circle signs up, and bump TERMS_VERSION when you do.
 */
export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro={`These terms govern your use of ${LEGAL.companyName}. By creating an account you agree to them.`}
    >
      <h2>1. The Service</h2>
      <p>
        {LEGAL.companyName} lets you set up AI agents for a business - answering its clients and
        carrying out work you define - and personal AI assistants for your own life. They act on
        your instructions and your content; you are responsible for what you configure them to do,
        for the content they are given, and for reviewing anything they produce before it reaches
        other people or the public.
      </p>

      <h2>2. Your account and your spaces</h2>
      <ul>
        <li>
          You must be at least 18 years old (or the age of majority where you live, if that is higher) to create an
          account. The Service is not directed at children, and a business must not use its agents to collect
          personal information from children under 13 (or the higher age its country sets).
        </li>
        <li>You must give accurate information and keep your credentials confidential.</li>
        <li>An account can own a business space, a personal space, or both. A personal space is for your own use and cannot be shared.</li>
        <li>A business owner is responsible for the people they invite and the roles they assign.</li>
        <li>You must not use the Service to break the law, to send unsolicited messages, or to interfere with the Service or other customers.</li>
        <li>
          If your agents talk to people for you, you must not present them as human. {LEGAL.companyName}&rsquo;s chat
          says it is an AI assistant and that conversations are saved; you must not remove or hide that, and you
          must tell people how their messages are used where the law requires it.
        </li>
        <li>
          You must not publish reviews, testimonials or results your agents wrote as if they came from real
          customers.
        </li>
      </ul>

      <h2>3. AI output</h2>
      <p>
        Agent output is generated by machine-learning models and can be wrong, incomplete or
        inappropriate. The Service provides review tools - draft-only mode, approvals, an audit
        log - and you agree to use them as appropriate for your use. {LEGAL.companyName} does not
        warrant the accuracy of any output. Assistants can help you think about money, health, legal
        or career questions, but they are not a financial adviser, doctor or lawyer, and their
        output is not professional advice. They never move money, buy, book or sign anything for
        you.
      </p>

      <h2>4. Plans, automatic renewal and cancellation</h2>
      <p>
        Paid plans are billed monthly in advance through our payment provider.{" "}
        <strong>
          A paid plan renews automatically every month, at the price shown when you subscribed,
          until you cancel.
        </strong>{" "}
        You can cancel at any time online, under Billing &rarr; Manage or cancel billing,
        with no need to contact us. Cancelling stops future charges; the plan stays active until
        the end of the month you have already paid for. We will tell you by email at least 7 days
        before any price change applies to you. Plan limits are described on the billing page and
        enforced by the Service. Fees are non-refundable except where the law requires otherwise.
      </p>

      <h2>5. Email your agents send</h2>
      <p>
        Email an agent sends goes out from your space, and you are its sender. You must
        only email people you have a lawful reason to contact and must follow the anti-spam law
        that applies to you. For a business, the Service adds your business name, the postal
        address you set, and an unsubscribe link to every agent email, and it stops emailing anyone
        who unsubscribes; do not remove or work around them.
      </p>

      <h2>6. Copyright complaints</h2>
      <p>
        If you believe content in the Service infringes your copyright, send a notice to our
        designated agent at {LEGAL.copyrightEmail} with: your signature; the work you say is
        infringed; where the infringing material is; your contact details; a statement that you
        believe in good faith the use is not authorised; and a statement, under penalty of perjury,
        that your notice is accurate and that you are the owner or authorised to act for them. We
        remove or disable material named in a valid notice and tell the person who provided it,
        who may send a counter-notice. We close the accounts of repeat infringers.
      </p>

      <h2>7. Your data</h2>
      <p>
        You retain all rights to the content you upload and the output your agents produce. You
        grant {LEGAL.companyName} the licence needed to operate the Service on your behalf,
        including sending your content to the model and search providers the Service uses. Our
        handling of personal data is described in the Privacy Policy.
      </p>

      <h2>8. Connected integrations and Google API services</h2>
      <p>
        If you choose to connect third-party integrations (such as Google Calendar or Gmail) to the Service:
      </p>
      <ul>
        <li>
          You authorize the Service to access and process the specific data necessary to provide the features you request
          (such as reading calendar events to check for clashes and create or move meetings, and reading email threads to draft replies you approve).
        </li>
        <li>
          Data received from Google APIs is used strictly to provide and improve these user-facing features. It is not sold, is not used for advertising,
          and is not used to train artificial intelligence (AI) or machine learning (ML) models.
        </li>
        <li>
          {"Desker's use and transfer to any other app of information received from Google APIs will adhere to the "}
          <a
            href="https://developers.google.com/terms/api-services-user-data-policy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent underline underline-offset-4 hover:text-accent-hover"
          >
            Google API Services User Data Policy (https://developers.google.com/terms/api-services-user-data-policy)
          </a>
          {", including the Limited Use requirements."}
        </li>
        <li>
          You can disconnect your connected accounts at any time from within the Service under Integrations or through your third-party account permissions,
          which immediately revokes access and deletes stored OAuth credentials from our systems.
        </li>
      </ul>

      <h2>9. Termination</h2>
      <p>
        You may delete your account, and every space you alone own, at any time from inside the
        Service. We may suspend or terminate accounts that
        breach these terms or put the Service or other customers at risk, with notice where
        practicable.
      </p>

      <h2>10. Liability</h2>
      <p>
        To the extent permitted by law, the Service is provided as is, and {LEGAL.companyName}
        &rsquo;s total liability for any claim is limited to the fees you paid in the twelve
        months before the claim arose.
      </p>

      <h2>11. Changes and contact</h2>
      <p>
        We may update these terms; material changes will be announced in the Service and take
        effect no sooner than 14 days after notice. These terms are governed by the laws of{" "}
        {LEGAL.jurisdiction}. Questions: {LEGAL.contactEmail}.
      </p>
    </LegalPage>
  );
}
