import type { Metadata } from "next";
import { LEGAL, TERMS_VERSION } from "@/lib/legal";

export const metadata: Metadata = { title: "Terms of Service" };

/**
 * TEMPLATE TEXT. This is a placeholder so the route, the link and the
 * acceptance record exist; the wording is a legal task. Replace it before
 * anyone outside your circle signs up, and bump TERMS_VERSION when you do.
 */
export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p>
        Version {TERMS_VERSION}. These terms govern your use of {LEGAL.companyName} (the
        &ldquo;Service&rdquo;). By creating an account you agree to them.
      </p>

      <h2>1. The Service</h2>
      <p>
        {LEGAL.companyName} lets you configure AI agents that answer your clients and carry out
        work you define. The agents act on your instructions and your content; you are
        responsible for what you configure them to do, for the content they are given, and for
        reviewing anything they produce before it reaches your clients or the public.
      </p>

      <h2>2. Your account and your organisation</h2>
      <ul>
        <li>You must give accurate information and keep your credentials confidential.</li>
        <li>An organisation owner is responsible for the people they invite and the roles they assign.</li>
        <li>You must not use the Service to break the law, to send unsolicited messages, or to interfere with the Service or other customers.</li>
      </ul>

      <h2>3. AI output</h2>
      <p>
        Agent output is generated by machine-learning models and can be wrong, incomplete or
        inappropriate. The Service provides review tools - draft-only mode, approvals, an audit
        log - and you agree to use them as appropriate for your use. {LEGAL.companyName} does not
        warrant the accuracy of any output.
      </p>

      <h2>4. Plans and payment</h2>
      <p>
        Paid plans are billed monthly in advance through our payment provider and renew until
        cancelled. Plan limits are described on the billing page and enforced by the Service.
        Fees are non-refundable except where the law requires otherwise.
      </p>

      <h2>5. Your data</h2>
      <p>
        You retain all rights to the content you upload and the output your agents produce. You
        grant {LEGAL.companyName} the licence needed to operate the Service on your behalf,
        including sending your content to the model and search providers the Service uses. Our
        handling of personal data is described in the Privacy Policy.
      </p>

      <h2>6. Termination</h2>
      <p>
        You may close your organisation at any time. We may suspend or terminate accounts that
        breach these terms or put the Service or other customers at risk, with notice where
        practicable.
      </p>

      <h2>7. Liability</h2>
      <p>
        To the extent permitted by law, the Service is provided as is, and {LEGAL.companyName}
        &rsquo;s total liability for any claim is limited to the fees you paid in the twelve
        months before the claim arose.
      </p>

      <h2>8. Changes and contact</h2>
      <p>
        We may update these terms; material changes will be announced in the Service and take
        effect no sooner than 14 days after notice. These terms are governed by the laws of{" "}
        {LEGAL.jurisdiction}. Questions: {LEGAL.contactEmail}.
      </p>
    </>
  );
}
